### ISSUE TITLE
hola, no corre

### ISSUE THREAD

**Issue by luisjimenez6245** [Screamice/nodejs-saxa#1]

**Comment by luisjimenez6245** [comment]
Quedo en espera, saludos.

**Comment by Screamice** [comment]
Inge, ya quedaron los cambios solo le comento que para correrlo tiene que modificar los valores del archivo config.js pues es el archivo que recolecta las claves para realizar las conexiones y por razones de seguridad no se suben a github

**Comment by luisjimenez6245** [comment]
Excelente, en un momento más lo pruebo y comento lo ocurrido.

**Comment by luisjimenez6245** [comment]
Muchas felicidades ingeniero, ya corrió el proyecto!

**Comment by luisjimenez6245** [comment]
Cierro el caso, saludos.
